### ISSUE TITLE
Broadwell doesn't have a config.plist page

### ISSUE THREAD

**Issue by axm2** [khronokernel/Opencore-Vanilla-Desktop-Guide#14]

**Comment by khronokernel** [comment]
Broadwell has like 3 desktop CPUs, I have no real desire to maintain an extra page for a platform with minimal users. Please use the Haswell section for your install.
If you're on a laptop, you shouldn't be using this guide as there's a lot of changes needed for those systems

**Comment by plasticbomb1986** [comment]
Well, im arrived here with the same question. i5-5675c. If there is not much difference, could it be mentioned around the corresponding part, that With Broadwell-H look for the haswell guide?

**Comment by AktasC** [comment]
> Broadwell has like 3 desktop CPUs, I have no real desire to maintain an extra page for a platform with minimal users. Please use the Haswell section for your install.
> If you're on a laptop, you shouldn't be using this guide as there's a lot of changes needed for those systems

Brodwell is important for laptops more than desktops, I still have a laptop from 2015 running fine on Linux and MacOS with Clover but I can't get OpenCore to work with it.    
Been on it for like half a week now, no issues whatsoever till I decided to go from Clover to OpenCore.   

It would be great if you could detail a bit on "There's a lot of changes needed for those" because from what I can see some people still managed to get their Thinkpads or Dell XPS's properly hackintoshed with OpenCore.
