### ISSUE TITLE
Clover Config's AppleRTC patch can be simplified

### ISSUE THREAD

**Issue by technicalflaw** [khronokernel/Opencore-Vanilla-Desktop-Guide#33]
The ```AppleRTC``` patch (in the ```Kernel and Kext Patches``` section of ```Clover-config.md```) is basically the same as the ```Disable RTC checksum update on poweroff``` patch that comes as part of OpenCore's ```sample.plist```.

It differs in that ```Disable RTC checksum update on poweroff``` disables the entire function, and the guide's binary patch just targets the specific part that updates the clock, but it's functionally the same, and because ```Disable RTC checksum update on poweroff``` uses a ```base``` value it's probably more stable.

**Comment by khronokernel** [comment]
Oh thank you for this, the AppleRTC patch I included was actually the one Acidanthera included in their sample.plist a while ago. I forgot they changed it a bit back when the RTC wake up bug showed up in 10.15.2 and they cleaned up the RTC patches they included

Fixed in latest commit: [6952b74
](https://github.com/khronokernel/Opencore-Vanilla-Desktop-Guide/commit/6952b745ac241cb746f54b20a182cb7fce9fb858)
