### ISSUE TITLE
"WriteFlash" setting for NVRAM

### ISSUE THREAD

**Issue by khronokernel** [khronokernel/Opencore-Vanilla-Desktop-Guide#55]
@filamento Hi, I would prefer if you opened a new issue instead of adding to the other one, reason being is every member of that issue is notified of your comment when in reality I'm the only one who needs to read it. 

Regarding your question, for emulated NRAM you shouldn't enable WriteFlash as you need working NVRAM for this to work correctly. Though something to note, some legacy hardware can support native NVRAM so I'd double check. My core2 Duo/Dell Studio 540 is running with native NVRAM but this isn't true for everything so double check. I'll likely add a note on this to the Emulated NVRAM page though I'm currently stockpiling changes atm in the 0.5.6 branch so you won't see the changes till either March 2nd or March 9th, whenever Vit plans to release 0.5.6(usually Mondays, start of the month)

**Comment by filamento** [comment]
Thank you for considering it for the guide!

Also, I've been battling with a stubborn hybrid EFI mainboard (Gigabyte GA-P67A-D3-B3 rev. 1.0 with bios F7) that I cannot get to work with OpenCore 0.55 and Catalina

Clover 5103 is able to boot and work correctly with this terrible board, but OpenCore will always hang, and after hanging it resets all my bios settings to factory defaults!

Hybrid EFI bioses are VERY annoying, because I also have to delete the "/EFI/BOOT" folder completely to avoid problems. Whenever that folder is present, the BIOS gets confused and all my boot entries disappear from Clover!

It's very frustrating. I'm also in doubt about the nvram in this board. Hybrid EFI bioses have very buggy support for efi variables and it's a real mess trying to delete or clean variables.

Do you think you could add some info about these horrible hybrid efi bioses in your guide?

Kind regards.

**Comment by filamento** [comment]
@khronokernel Sir, do you have plans to include a "Sandy Bridge" section in your guide?

Also, Apple doesn't support any Mac with Sandy Bridge on MacOS Catalina, so we are forced to use "iMac13,2" in SMBIOS.

But all iMac13,2 models have Ivy Bridge cpus inside! Do you know what stability problems could this bring?

Regards.

**Comment by khronokernel** [comment]
@filamento No plans on support for legacy hardware besides the little bits of info sprinkled in, I'm mainly adding info that wouldn't be obvious for many users like AppleUsbKbDxe.efi and HfsPlusLegacy.efi. And many of the quirks are mentioned with extra info so you can use a bit of critical thinking on what to enable

For SandyBridge specifically, just follow Ivy's guide and ignore the DeviceProperties as HD 3000 is no longer supported
