### ISSUE TITLE
AppleRTC OpenCore patch on 10.15.4

### ISSUE THREAD

**Issue by eramdam** [khronokernel/Opencore-Vanilla-Desktop-Guide#61]
Hey!

First of all thanks for the amazing guide 😄 

I recently upgraded to 10.15.4 beta, and I noticed that the [AppleRTC patch](https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/troubleshooting/troubleshooting#bios-reset-or-sent-into-safemode-after-reboot-shutdown) to fix the BIOS being sent in safe mode doesn't work anymore.

Weirdly enough, my OpenCore logs suggest that it's being applied successfully (see https://gist.github.com/eramdam/ff09b2de23a243af0d40895a355637a2#file-opencore-log-txt-L496-L497) but as far as I can tell it doesn't work because my BIOS still goes into safe mode after a poweroff 😅 

Here's the patch in my config.plist just in case https://github.com/eramdam/hackintosh/blob/0d9b7f3d893d80a244d35c6ef55ced39ccfdf9b7/EFI/OC/config.plist#L469-L496

Is there any way to fix it? My assumption is that AppleRTC.kext changed between .3 and .4 and that the patch needs to be updated somehow. I can send the kext if that helps.

**Comment by khronokernel** [comment]
Had a bit of free time to play around with it, my Dell Studio 540(core2 Quad) on 10.15.4 beta 4 still works so I played a bit more and checked with IDA to see if the function changed at all. So to start, I made sure `__ZN8AppleRTC14updateChecksumEv` was unmodified which from the image it hasn't in how it would function(returning `C3`/1 will skip the function, as it's been told it's done. We're not calling the JNZ so that small change doesn't matter to us):
![](https://cdn.discordapp.com/attachments/683011276938543134/687733731137683602/Screen_Shot_2020-03-12_at_12.19.17_PM.png)
I suppose the next step is to try and figure out what's causing the issue, problem is there many places that call RTC write and that's out of my scope unfortunately.

Hopefully not to leave you stranded, you can play around with [RTCMemoryFixup](https://github.com/acidanthera/RTCMemoryFixup) with the patch you're already using. But besides that, forums and trying to see if others have similar issues is your best bet

**Comment by eramdam** [comment]
I tried RTCMemoryFixup, with, what I thought were the wrong offsets because macOS was complaining about a wrong clock but after messing around with the offsets, and even removing RTCMemoryFixup... the issue doesn't happen anymore even with the patch disabled 🤔 

So I'm really not sure what to think and I'm too lazy to erase everything and figure this out so I guess I'll wait to see the stable release of 10.15.4 to see if there's really a difference 😅

**Comment by eramdam** [comment]
> I tried RTCMemoryFixup, with, what I thought were the wrong offsets because macOS was complaining about a wrong clock but after messing around with the offsets, and even removing RTCMemoryFixup... the issue doesn't happen anymore even with the patch disabled 🤔
> 
> So I'm really not sure what to think and I'm too lazy to erase everything and figure this out so I guess I'll wait to see the stable release of 10.15.4 to see if there's really a difference 😅

Nevermind, turns out i wasn't testing this whole thing properly because the safe mode issue occurs when going from macOS and doing a restart, but _not_ when going from macOS and doing a shut down. 

I'll try RTCMemoryFixup again and update in this thread so at least if i find something, someone with the same issue can benefit from a fix 😄

**Comment by TomDai** [comment]
Hi there, have you found a fix yet? I'm experiencing the same issue after upgrading from 10.15.3 to 10.15.4. Also it boots into safe mode after restart _and_ shutdown for me..

**Comment by eramdam** [comment]
I haven't had time to figure it out to be completely honest. On my setup it goes into safe mode quite inconsistently so it makes it very hard to know if whatever I'm doing fixes the underlying issue 😬

**Comment by vovinacci** [comment]
This is tracked in https://github.com/acidanthera/bugtracker/issues/765
